# -*- coding: utf-8 -*-
"""pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVxW5xAyc7jcPR2MYyOaPdnaVk-cU1Hl
"""

import pandas as pd

!pip install fundamentus yfinance

import yfinance as yf

# Definindo a carteira de ações
carteira_yf = ['ABEV3.SA', 'B3SA3.SA', 'GGBR4.SA', 'ITSA4.SA',
               'PETR4.SA', 'RENT3.SA', 'SUZB3.SA', 'VALE3.SA', 'WEGE3.SA']

# Carregando os dados da carteira
df = yf.download(carteira_yf, start="2022-08-01", end="2023-08-01")

# Passando os ativos para o multindex do df
cotacoes = df.stack(level = 1)
cotacoes

cotacoes = cotacoes.reset_index().rename(columns={"Ticker": "Ativo"})

cotacoes

cotacoes.info()

cotacoes.reset_index(drop=True, inplace=True)

print(cotacoes.index.name)
print(cotacoes.columns.name)

cotacoes.columns.name = None

cotacoes

import fundamentus

weg = fundamentus.get_papel('WEGE3')
weg

carteira_fund = ["ABEV3", "B3SA3", "AXIA3", "GGBR4", "ITSA4",
                 "PETR4", "RENT3", "SUZB3", "VALE3", "WEGE3"]

# Criando um df com algumas infos da carteira
ind = fundamentus.get_papel(carteira_fund)[['Setor', 'Cotacao', 'Min_52_sem', 'Max_52_sem', 'Valor_de_mercado',
                                            'Nro_Acoes', 'Patrim_Liq','Receita_Liquida_12m','Receita_Liquida_3m',
                                            'Lucro_Liquido_12m', 'Lucro_Liquido_3m']]
ind.head(3)

ind = ind.reset_index()

ind.rename(columns = {'index':'Ativo'}, inplace = True)

ind

import pandas as pd
# Alterando colunas object para numeric
colunas = ['Cotacao', 'Min_52_sem', 'Max_52_sem', 'Valor_de_mercado', 'Nro_Acoes', 'Patrim_Liq',
           'Receita_Liquida_12m', 'Receita_Liquida_3m', 'Lucro_Liquido_12m', 'Lucro_Liquido_3m']
ind[colunas] = ind[colunas].apply(pd.to_numeric, errors='coerce', axis=1)
ind.head()

ind2 = fundamentus.get_resultado_raw().reset_index()

ind2 = ind2.query('papel in @carteira_fund')

ind2 = ind2[['papel','P/L', 'Div.Yield','P/VP','ROE']].reset_index(drop=True)

ind2.rename(columns={'papel': 'Ativo','Div.Yield':'DY'}, inplace= True)
ind2.head()

indicadores = pd.merge(ind, ind2, on = 'Ativo')

indicadores['LPA'] = (indicadores['Lucro_Liquido_12m'] / indicadores['Nro_Acoes']).round(2)
indicadores['VPA'] = (indicadores['Patrim_Liq'] / indicadores['Nro_Acoes']).round(2)

indicadores.to_excel("indicadores.xlsx", index=False)
cotacoes.to_excel("cotacoes.xlsx", index=False)